// File generated by FlutterFire CLI.

// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'

show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

///

/// Example:

/// ```dart

/// import 'firebase_options.dart';

/// // ...

/// await Firebase.initializeApp(

/// options: DefaultFirebaseOptions.currentPlatform,

/// );

/// ```

class DefaultFirebaseOptions {

static FirebaseOptions get currentPlatform {

if (kIsWeb) {

return web;

}

switch (defaultTargetPlatform) {

case TargetPlatform.android:

return android;

case TargetPlatform.iOS:

return ios;

case TargetPlatform.macOS:

return macos;

case TargetPlatform.windows:

return windows;

case TargetPlatform.linux:

throw UnsupportedError(

'DefaultFirebaseOptions have not been configured for linux - '

'you can reconfigure this by running the FlutterFire CLI again.',

);

default:

throw UnsupportedError(

'DefaultFirebaseOptions are not supported for this platform.',

);

}

}

static const FirebaseOptions web = FirebaseOptions(

apiKey: 'AIzaSyCQY4eeWsuZwXBCw4ad5LD88f0QglKPAKY',

appId: '1:482530908:web:48b7a693aa85456495f899',

messagingSenderId: '482530908',

projectId: 'billsplit-fff70',

authDomain: 'billsplit-fff70.firebaseapp.com',

storageBucket: 'billsplit-fff70.firebasestorage.app',

);

static const FirebaseOptions android = FirebaseOptions(

apiKey: 'AIzaSyD1fDtrssCNUE9yr_IuJY1lSgLBPolSspY',

appId: '1:482530908:android:552a42718f75d46595f899',

messagingSenderId: '482530908',

projectId: 'billsplit-fff70',

storageBucket: 'billsplit-fff70.firebasestorage.app',

);

static const FirebaseOptions ios = FirebaseOptions(

apiKey: 'AIzaSyAGQyY0pQU5JqUO9rsxcBx0H1Zji01Dbhc',

appId: '1:482530908:ios:e80309f5b7eaca9795f899',

messagingSenderId: '482530908',

projectId: 'billsplit-fff70',

storageBucket: 'billsplit-fff70.firebasestorage.app',

iosBundleId: 'com.example.billsplit',

);

static const FirebaseOptions macos = FirebaseOptions(

apiKey: 'AIzaSyAGQyY0pQU5JqUO9rsxcBx0H1Zji01Dbhc',

appId: '1:482530908:ios:e80309f5b7eaca9795f899',

messagingSenderId: '482530908',

projectId: 'billsplit-fff70',

storageBucket: 'billsplit-fff70.firebasestorage.app',

iosBundleId: 'com.example.billsplit',

);

static const FirebaseOptions windows = FirebaseOptions(

apiKey: 'AIzaSyCQY4eeWsuZwXBCw4ad5LD88f0QglKPAKY',

appId: '1:482530908:web:ce57ff2547b361a695f899',

messagingSenderId: '482530908',

projectId: 'billsplit-fff70',

authDomain: 'billsplit-fff70.firebaseapp.com',

storageBucket: 'billsplit-fff70.firebasestorage.app',

);

}

